Repository Celestial-Project/Celestial-Legacy, pull requests merged in 2022-07, with the labels that each got.

#9 Fix window reload bug
  cli_tester.py
  main.py
Labels: bug

#7 -update : responses.json & responses_th.json
  responses/responses.json
  responses/responses_th.json
Labels: enhancement

#10 update : responses.json & responses_th.json
  responses/responses.json
  responses/responses_th.json
Labels: enhancement

#16 Adding festival based intents & handler
  chat_response.py
  responses/festivals.json
  responses/festivals_th.json
Labels: enhancement, help wanted
