Repository Celestial-Project/Celestial-Legacy, pull requests merged in 2023-12, with the labels that each got.

#52 edited my mistake
  responses/festivals.json
  responses/festivals_th.json
Labels: bug

#50 Add some words krub!
  responses/badwords.json
  responses/festivals_th.json
  responses/responses_th.json
Labels: enhancement

#49 Add suggestion system to Celestial Legacy
  main.py
  requirements.txt
  utils/database.py
  utils/modals/suggestion_modal.py
Labels: enhancement, Feature request, DL-feature
